name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          repository: 'learnin9/portsip-voip-sdk-sample-for-android'
      - name: Checkout the config
        uses: actions/checkout@v3
        with: 
          path: 'config'
      - name: Setup ENV
        run: |
          cp -R config/google-services.json SIPSample_AndroidStudio/SIPSample/google-services.js
          chmod 777 SIPSample/google-services.js
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build the app
        working-directory: ./SIPSample_AndroidStudio
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: ./**/*.apk

