name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          repository: 'hugeek95/portSipKotlin'
          
      - name: Checkout config
        uses: actions/checkout@v3
        with: 
          path: 'config'
          
      - name: Setup env
        run: |
          cp -R config/google-services.json google-services.js
          
      - name: Build app
        uses: Raul6469/android-gradle-action@2.0.0
        with: 
          script: assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: ./**/*.apk

