name: android_build_react

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          repository: 'evollu/react-native-fcm'
          
      - name: Checkout config
        uses: actions/checkout@v3
        with: 
          path: 'config'
          
      - name: Setup env
        run: |
          chmod 777 config/*
          cp -f config/google-services.json ./Examples/simple-fcm-client/android/app/
          cp -f config/AndroidManifest.xml  ./Examples/simple-fcm-client/android/app/src/main/
          cat /home/runner/work/android-build/android-build/Examples/simple-fcm-client/android/app/src/main/AndroidManifest.xml
          sed 's/16/19/g' -i ./Examples/simple-fcm-client/android/app/build.gradle
      - name: Setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Build app
        working-directory: ./Examples/simple-fcm-client
        run: |
          npm install --legacy-peer-deps
          cd android
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
          
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: ./**/*.apk

